#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-slim
Version  : 3.0.6
Release  : 7
URL      : https://rubygems.org/downloads/slim-3.0.6.gem
Source0  : https://rubygems.org/downloads/slim-3.0.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-slim-bin
BuildRequires : ruby
BuildRequires : rubygem-asciidoctor
BuildRequires : rubygem-builder
BuildRequires : rubygem-creole
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-redcarpet
BuildRequires : rubygem-sass
BuildRequires : rubygem-temple
BuildRequires : rubygem-tilt

%description
# Slim
[![Gem Version](https://img.shields.io/gem/v/slim.svg)](http://rubygems.org/gems/slim) [![Build Status](https://img.shields.io/travis/slim-template/slim.svg?branch=master)](http://travis-ci.org/slim-template/slim) [![Dependency Status](https://img.shields.io/gemnasium/slim-template/slim.svg?travis)](https://gemnasium.com/slim-template/slim) [![Code Climate](https://img.shields.io/codeclimate/github/slim-template/slim.svg)](https://codeclimate.com/github/slim-template/slim) [![Gittip donate button](https://img.shields.io/gratipay/bevry.svg)](https://www.gittip.com/min4d/ "Donate weekly to this project using Gittip")
[![Flattr donate button](https://raw.github.com/balupton/flattr-buttons/master/badge-89x18.gif)](https://flattr.com/submit/auto?user_id=min4d&url=http%3A%2F%2Fslim-lang.org%2F "Donate monthly to this project using Flattr")

%package bin
Summary: bin components for the rubygem-slim package.
Group: Binaries

%description bin
bin components for the rubygem-slim package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n slim-3.0.6
gem spec %{SOURCE0} -l --ruby > rubygem-slim.gemspec

%build
gem build rubygem-slim.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
slim-3.0.6.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/slim-3.0.6 && rake --trace test && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/slim-3.0.6.gem
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/CodeAttributes/cdesc-CodeAttributes.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/CodeAttributes/on_html_attr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/CodeAttributes/on_html_attrs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/CodeAttributes/on_slim_attrvalue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Command/cdesc-Command.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Command/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Command/process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Command/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Command/set_opts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Controls/cdesc-Controls.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Controls/on_slim_control-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Controls/on_slim_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Controls/on_slim_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/DoInserter/cdesc-DoInserter.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/DoInserter/on_slim_control-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/DoInserter/on_slim_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/ERBConverter/Temple/Filters/cdesc-Filters.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/ERBConverter/Temple/Generators/cdesc-Generators.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/ERBConverter/Temple/cdesc-Temple.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/ERBConverter/cdesc-ERBConverter.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/ERBEngine/cdesc-ERBEngine.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/ERBEngine/erb_parser-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/ERBEngine/on_slim_embedded-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/Engine/cdesc-Engine.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/Engine/collect_newlines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/Engine/collect_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/InterpolateTiltEngine/cdesc-InterpolateTiltEngine.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/InterpolateTiltEngine/collect_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/InterpolateTiltEngine/interpolation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/InterpolateTiltEngine/output_protector-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/InterpolateTiltEngine/tilt_render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/JavaScriptEngine/cdesc-JavaScriptEngine.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/JavaScriptEngine/on_slim_embedded-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/PrecompiledTiltEngine/cdesc-PrecompiledTiltEngine.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/PrecompiledTiltEngine/tilt_render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/RubyEngine/cdesc-RubyEngine.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/RubyEngine/on_slim_embedded-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/SassEngine/cdesc-SassEngine.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/SassEngine/tilt_render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/TagEngine/cdesc-TagEngine.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/TagEngine/on_slim_embedded-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/TiltEngine/cdesc-TiltEngine.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/TiltEngine/on_slim_embedded-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/TiltEngine/tilt_render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/cdesc-Embedded.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/enabled%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/engines-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/normalize_engine_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/on_slim_embedded-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Embedded/register-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/EndInserter/append_end-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/EndInserter/cdesc-EndInserter.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/EndInserter/control%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/EndInserter/on_multi-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Engine/Temple/Generators/cdesc-Generators.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Engine/Temple/HTML/cdesc-HTML.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Engine/Temple/cdesc-Temple.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Engine/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Engine/call_without_include-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Engine/cdesc-Engine.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Filter/cdesc-Filter.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Filter/on_slim_control-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Filter/on_slim_embedded-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Filter/on_slim_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Filter/on_slim_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Grammar/cdesc-Grammar.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Include/cdesc-Include.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Include/find_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Include/on_html_tag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Interpolation/cdesc-Interpolation.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Interpolation/on_slim_interpolate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/Scope/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/Scope/cdesc-Scope.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/Scope/dict-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/Scope/has_key%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/Scope/instance_variable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/Scope/lambda-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/Scope/lookup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/Scope/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/Scope/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/cdesc-Context.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/inverted_section-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/lambda-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/new_scope-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/scope-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/section-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/Context/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/access-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/cdesc-LogicLess.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/on_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/on_dynamic-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/on_slim_attrvalue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/on_slim_control-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/on_slim_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/LogicLess/on_slim_splat-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/NewlineCollector/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/NewlineCollector/cdesc-NewlineCollector.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/NewlineCollector/on_newline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/OutputProtector/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/OutputProtector/cdesc-OutputProtector.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/OutputProtector/on_slim_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/OutputProtector/on_static-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/OutputProtector/unprotect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/SyntaxError/cdesc-SyntaxError.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/SyntaxError/column-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/SyntaxError/error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/SyntaxError/file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/SyntaxError/line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/SyntaxError/lineno-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/SyntaxError/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/SyntaxError/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/cdesc-Parser.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/deprecated_syntax-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/expect_next_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/get_indent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/next_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/parse_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/parse_broken_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/parse_comment_block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/parse_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/parse_line_indicators-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/parse_quoted_attribute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/parse_ruby_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/parse_tag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/parse_text_block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/syntax_error%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Parser/unknown_line_indicator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Escaper/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Escaper/cdesc-Escaper.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Escaper/on_slim_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Escaper/on_static-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Filter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Filter/cdesc-Filter.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Filter/chars_re-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Filter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Filter/on_multi-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Filter/on_slim_interpolate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Filter/on_slim_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Filter/on_slim_text_inline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Parser/cdesc-Parser.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Parser/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/Parser/unknown_line_indicator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Smart/cdesc-Smart.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Builder/attr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Builder/build_attrs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Builder/build_tag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Builder/cdesc-Builder.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Builder/code_attr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Builder/escape_html-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Builder/hyphen_attr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Builder/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Builder/splat_attrs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Filter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Filter/cdesc-Filter.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Filter/make_builder-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Filter/on_html_attrs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Filter/on_html_tag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/Filter/splat%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Splat/cdesc-Splat.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/TextCollector/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/TextCollector/cdesc-TextCollector.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/TextCollector/on_slim_interpolate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/DynamicTranslator/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/DynamicTranslator/cdesc-DynamicTranslator.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/DynamicTranslator/on_slim_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/DynamicTranslator/on_static-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/StaticTranslator/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/StaticTranslator/cdesc-StaticTranslator.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/StaticTranslator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/StaticTranslator/on_slim_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/StaticTranslator/on_static-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/cdesc-Translator.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/i18n_key-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/i18n_text-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/Translator/on_slim_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/Slim/cdesc-Slim.ri
/usr/lib64/ruby/gems/2.2.0/doc/slim-3.0.6/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/.yardopts
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/CHANGES
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/README.jp.md
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/README.md
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/benchmarks/context.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/benchmarks/profile-parser.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/benchmarks/profile-render.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/benchmarks/run-benchmarks.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/benchmarks/run-diffbench.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/benchmarks/view.erb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/benchmarks/view.haml
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/benchmarks/view.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/bin/slimrb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/doc/include.md
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/doc/jp/include.md
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/doc/jp/logic_less.md
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/doc/jp/smart.md
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/doc/jp/translator.md
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/doc/logic_less.md
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/doc/smart.md
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/doc/translator.md
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/code_attributes.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/command.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/controls.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/do_inserter.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/embedded.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/end_inserter.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/engine.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/erb_converter.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/grammar.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/include.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/interpolation.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/logic_less.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/logic_less/context.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/logic_less/filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/parser.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/smart.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/smart/escaper.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/smart/filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/smart/parser.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/splat/builder.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/splat/filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/template.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/translator.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/lib/slim/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/slim.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_code_blocks.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_code_escaping.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_code_evaluation.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_code_output.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_code_structure.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_commands.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_embedded_engines.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_encoding.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_erb_converter.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_html_attributes.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_html_escaping.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_html_structure.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_parser_errors.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_pretty.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_ruby_errors.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_slim_template.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_tabs.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_text_interpolation.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_thread_options.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/core/test_unicode.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/include/files/recursive.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/include/files/slimfile.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/include/files/subdir/test.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/include/files/textfile
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/include/test_include.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/literate/TESTS.md
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/literate/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/literate/run.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/logic_less/test_logic_less.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/controllers/application_controller.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/controllers/entries_controller.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/controllers/slim_controller.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/helpers/application_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/models/entry.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/entries/edit.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/layouts/application.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/slim/_partial.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/slim/content_for.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/slim/erb.html.erb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/slim/form_for.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/slim/helper.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/slim/integers.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/slim/no_layout.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/slim/normal.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/slim/partial.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/slim/splat.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/slim/thread_options.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/slim/variables.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/app/views/slim/xml.slim
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/config.ru
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/config/application.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/config/boot.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/config/environment.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/config/environments/test.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/config/initializers/backtrace_silencers.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/config/initializers/inflections.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/config/initializers/mime_types.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/config/initializers/secret_token.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/config/initializers/session_store.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/config/locales/en.yml
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/config/routes.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/script/rails
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/test/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/rails/test/test_slim.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/smart/test_smart_text.rb
/usr/lib64/ruby/gems/2.2.0/gems/slim-3.0.6/test/translator/test_translator.rb
/usr/lib64/ruby/gems/2.2.0/specifications/slim-3.0.6.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/slimrb
